import Foundation

let citiesStub = [
    "Tokyo",
    "Paris",
    "London",
    "New York",
    "Bangkok",
    "Istanbul",
    "Dubai",
    "Singapore",
    "Kuala Lumpur",
    "Seoul",
    "Barcelona",
    "Rome",
    "Los Angeles",
    "Osaka",
    "Moscow",
    "Sydney",
    "Rio de Janeiro",
    "Berlin",
    "Shanghai",
    "Amsterdam",
    "Toronto",
    "Hong Kong",
    "Mexico City",
    "Buenos Aires",
    "Cairo",
    "Mumbai",
    "Cape Town",
    "Dublin",
    "Prague",
    "Athens",
    "Athens",
]
